version: '3.4'

services:
  api-pizza:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MongoDb: 'mongodb://mongodb:27017'
      DatabaseName: 'Pizza'
      CollectionName: 'Pizza'
    ports:
      - 5000:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  mongodb:
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    restart: always
      
volumes:
  mongodb_data: 